export interface IKeyCap {
    size: number;
    upper?: string;
    lower?: string;
    center?: string;
}

export const KeyCapsData: IKeyCap[][] = [
    [
        {size: 1, upper: `~`, lower: `\``},
        {size: 1, upper: `!`, lower: `1`},
        {size: 1, upper: `@`, lower: `2`},
        {size: 1, upper: `#`, lower: `3`},
        {size: 1, upper: `$`, lower: `4`},
        {size: 1, upper: `%`, lower: `5`},
        {size: 1, upper: `^`, lower: `6`},
        {size: 1, upper: `&`, lower: `7`},
        {size: 1, upper: `*`, lower: `8`},
        {size: 1, upper: `(`, lower: `9`},
        {size: 1, upper: `)`, lower: `0`},
        {size: 1, upper: `_`, lower: `-`},
        {size: 1, upper: `+`, lower: `=`},
        {size: 2},
    ],
    [
        {size: 1.5},
        {size: 1, upper: `Q`, lower: `q`},
        {size: 1, upper: `W`, lower: `w`},
        {size: 1, upper: `E`, lower: `e`},
        {size: 1, upper: `R`, lower: `r`},
        {size: 1, upper: `T`, lower: `t`},
        {size: 1, upper: `Y`, lower: `y`},
        {size: 1, upper: `U`, lower: `u`},
        {size: 1, upper: `I`, lower: `i`},
        {size: 1, upper: `O`, lower: `o`},
        {size: 1, upper: `P`, lower: `p`},
        {size: 1, upper: `{`, lower: `[`},
        {size: 1, upper: `}`, lower: `]`},
        {size: 1.5, upper: `|`, lower: `\\`},
    ],
    [
        {size: 1.75},
        {size: 1, upper: `A`, lower: `a`},
        {size: 1, upper: `S`, lower: `s`},
        {size: 1, upper: `D`, lower: `d`},
        {size: 1, upper: `F`, lower: `f`},
        {size: 1, upper: `G`, lower: `g`},
        {size: 1, upper: `H`, lower: `h`},
        {size: 1, upper: `J`, lower: `j`},
        {size: 1, upper: `K`, lower: `k`},
        {size: 1, upper: `L`, lower: `l`},
        {size: 1, upper: `:`, lower: `;`},
        {size: 1, upper: `"`, lower: `'`},
        {size: 2.25, center: `Enter`},
    ],
    [
        {size: 2.25, center: `Shift`},
        {size: 1, upper: `Z`, lower: `z`},
        {size: 1, upper: `X`, lower: `x`},
        {size: 1, upper: `C`, lower: `c`},
        {size: 1, upper: `V`, lower: `v`},
        {size: 1, upper: `B`, lower: `b`},
        {size: 1, upper: `N`, lower: `n`},
        {size: 1, upper: `M`, lower: `m`},
        {size: 1, upper: `<`, lower: `,`},
        {size: 1, upper: `>`, lower: `.`},
        {size: 1, upper: `?`, lower: `/`},
        {size: 2.75},
    ],
    [
        {size: 1.25},
        {size: 1.25},
        {size: 1.25},
        {size: 6.25, center: `SpaceBar`},
        {size: 1.25},
        {size: 1.25},
        {size: 1.25},
        {size: 1.25},
    ]
];